<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/08 04:36:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mongodb.masternode.com;port=3306;dbname=orangehrm_mysql',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
